version: "3.3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 7000:7000
    expose:
      - 7000
    environment:
      - PORT=7000
    restart: always
